%% export_backtrajectories_with_forcing_and_draft.m
%
% Create sharable NetCDF files containing Barents Sea back trajectories
% together with interpolated forcing and estimated ice draft.
%
% The script creates one derived NetCDF file for each mooring, M1 and M2.
% The original trajectory NetCDF files are not modified.
%
% Included variables:
%   t                      trajectory time [days since 1970-01-01]
%   lat                    latitude [degrees_north]
%   lon                    longitude [degrees_east]
%   air_temperature_2m      ERA5 2-m air temperature along trajectory [deg C]
%   snow_depth_smlg         SM-LG snow depth along trajectory [m]
%   draft_fdd_m             FDD + OHF draft along trajectory [m]
%   draft_therm_m           thermal-resistance draft along trajectory [m]
%   draft_fdd_arrival_m     FDD + OHF draft at arrival [m]
%   draft_therm_arrival_m   thermal-resistance draft at arrival [m]
%
% Note:
%   Row 1 corresponds to the arrival location/time.
%   Increasing row index follows the back trajectory backward in time.

clear; clc; close all

% Paths

projectDir = 'C:\Users\evsalg001\Documents\MATLAB\Sonar Barents Sea';

processedDir = fullfile(projectDir,'data','processed');

era5File = fullfile(processedDir, ...
    'ERA5_T2m_on_backtrajectories.mat');

snowFile = fullfile(processedDir, ...
    'SnowDepth_LG_on_backtrajectories.mat');

fddFile = fullfile(processedDir, ...
    'trajectory_FDD_three_approaches_M1_M2.mat');

thermFile = fullfile(processedDir, ...
    'trajectory_thermal_resistance_SMLG_M1_M2.mat');

outFile_M1 = fullfile(processedDir, ...
    'back_trajectories_M1_with_forcing_and_draft.nc');

outFile_M2 = fullfile(processedDir, ...
    'back_trajectories_M2_with_forcing_and_draft.nc');

% Load processed data

era5 = load(era5File, ...
    'Ttraj_C','traj_time','lat_all','lon_all','t_all', ...
    'idx_M1','idx_M2','nM1','nM2');

snow = load(snowFile, ...
    'Hs_traj');

fdd = load(fddFile, ...
    'h_ohf_step_m','h_ohf_m','draft_ohf_m');

therm = load(thermFile, ...
    'h_therm_step_m','h_therm_m','draft_therm_m');

% Create full-trajectory draft variables

% FDD + OHF draft along the full trajectory.
draft_fdd_step_m = 0.85 .* fdd.h_ohf_step_m;

% Thermal-resistance draft along the full trajectory.
draft_therm_step_m = 0.85 .* therm.h_therm_step_m;

% Arrival draft estimates.
% Row 1 is arrival, but use the already saved arrival variables where available.
draft_fdd_arrival_m = fdd.draft_ohf_m;
draft_therm_arrival_m = therm.draft_therm_m;

% Basic consistency checks

check_same_size(era5.Ttraj_C, snow.Hs_traj, ...
    'Ttraj_C','Hs_traj');

check_same_size(era5.Ttraj_C, draft_fdd_step_m, ...
    'Ttraj_C','draft_fdd_step_m');

check_same_size(era5.Ttraj_C, draft_therm_step_m, ...
    'Ttraj_C','draft_therm_step_m');

fprintf('Input arrays have consistent sizes: %d time steps x %d trajectories\n', ...
    size(era5.Ttraj_C,1), size(era5.Ttraj_C,2));

% Write M1 product

write_product_netcdf( ...
    outFile_M1, ...
    'M1', ...
    era5.t_all(:,era5.idx_M1), ...
    era5.lat_all(:,era5.idx_M1), ...
    era5.lon_all(:,era5.idx_M1), ...
    era5.Ttraj_C(:,era5.idx_M1), ...
    snow.Hs_traj(:,era5.idx_M1), ...
    draft_fdd_step_m(:,era5.idx_M1), ...
    draft_therm_step_m(:,era5.idx_M1), ...
    draft_fdd_arrival_m(era5.idx_M1), ...
    draft_therm_arrival_m(era5.idx_M1));

% Write M2 product

write_product_netcdf( ...
    outFile_M2, ...
    'M2', ...
    era5.t_all(:,era5.idx_M2), ...
    era5.lat_all(:,era5.idx_M2), ...
    era5.lon_all(:,era5.idx_M2), ...
    era5.Ttraj_C(:,era5.idx_M2), ...
    snow.Hs_traj(:,era5.idx_M2), ...
    draft_fdd_step_m(:,era5.idx_M2), ...
    draft_therm_step_m(:,era5.idx_M2), ...
    draft_fdd_arrival_m(era5.idx_M2), ...
    draft_therm_arrival_m(era5.idx_M2));

fprintf('\nCreated NetCDF files:\n')
fprintf('  %s\n', outFile_M1)
fprintf('  %s\n', outFile_M2)

% Optional quick check

disp(' ')
disp('M1 file info:')
ncdisp(outFile_M1)

%% Local functions

function write_product_netcdf(outFile, mooringName, ...
    t, lat, lon, air_temperature_2m, snow_depth_smlg, ...
    draft_fdd_m, draft_therm_m, ...
    draft_fdd_arrival_m, draft_therm_arrival_m)

    if exist(outFile,'file')
        delete(outFile)
    end

    [nStep,nTraj] = size(t);

    % Coordinate/index variables

    nccreate(outFile,'time_step', ...
        'Dimensions',{'time_step',nStep}, ...
        'Datatype','int32', ...
        'Format','netcdf4');

    ncwrite(outFile,'time_step',int32(1:nStep));
    ncwriteatt(outFile,'time_step','long_name','trajectory time-step index');
    ncwriteatt(outFile,'time_step','comment', ...
        'Index only. Row 1 corresponds to arrival; increasing index follows the back trajectory backward in time.');

    nccreate(outFile,'trajectory', ...
        'Dimensions',{'trajectory',nTraj}, ...
        'Datatype','int32');

    ncwrite(outFile,'trajectory',int32(1:nTraj));
    ncwriteatt(outFile,'trajectory','long_name','trajectory index');

    % Basic trajectory variables

    write_2d_var(outFile,'t',t, ...
        'trajectory time', ...
        'days since 1970-01-01 00:00:00', ...
        'Preserved from processed back-trajectory data. Row 1 is the arrival time.');

    write_2d_var(outFile,'lat',lat, ...
        'latitude', ...
        'degrees_north', ...
        'Trajectory latitude. Row 1 is the arrival location.');

    write_2d_var(outFile,'lon',lon, ...
        'longitude', ...
        'degrees_east', ...
        'Trajectory longitude. Row 1 is the arrival location.');

    % Derived forcing variables

    write_2d_var(outFile,'air_temperature_2m',air_temperature_2m, ...
        'ERA5 2-m air temperature interpolated to trajectory', ...
        'degree_Celsius', ...
        'Interpolated linearly in space and time from ERA5 t2m.');

    ncwriteatt(outFile,'air_temperature_2m','source','ERA5 t2m');

    write_2d_var(outFile,'snow_depth_smlg',snow_depth_smlg, ...
        'SM-LG snow depth interpolated to trajectory', ...
        'm', ...
        'Interpolated linearly in space and time from SnowModel-LG / MERRA2-derived snow depth.');

    ncwriteatt(outFile,'snow_depth_smlg','source','SnowModel-LG');

    % Derived draft variables along full trajectories

    write_2d_var(outFile,'draft_fdd_m',draft_fdd_m, ...
        'ice draft estimated from FDD model with ocean heat flux correction', ...
        'm', ...
        'Full-trajectory estimate. Row 1 corresponds to arrival; increasing row index follows the back trajectory backward in time.');

    ncwriteatt(outFile,'draft_fdd_m','method', ...
        'FDD thickness model with monthly ocean heat flux correction; draft estimated as 0.85 times ice thickness.');

    write_2d_var(outFile,'draft_therm_m',draft_therm_m, ...
        'ice draft estimated from thermal-resistance model', ...
        'm', ...
        'Full-trajectory estimate. Row 1 corresponds to arrival; increasing row index follows the back trajectory backward in time.');

    ncwriteatt(outFile,'draft_therm_m','method', ...
        'Thermal-resistance growth model forced by ERA5 air temperature and SM-LG snow depth; draft estimated as 0.85 times ice thickness.');

    % Arrival-only convenience variables

    write_1d_var(outFile,'draft_fdd_arrival_m',draft_fdd_arrival_m, ...
        'arrival ice draft estimated from FDD model with ocean heat flux correction', ...
        'm', ...
        'Convenience variable equal to draft_fdd_m(1,:).');

    write_1d_var(outFile,'draft_therm_arrival_m',draft_therm_arrival_m, ...
        'arrival ice draft estimated from thermal-resistance model', ...
        'm', ...
        'Convenience variable equal to draft_therm_m(1,:).');

    % Global attributes

    ncwriteatt(outFile,'/','title', ...
        'Barents Sea back trajectories with air temperature, snow depth, and estimated ice draft');

    ncwriteatt(outFile,'/','mooring',mooringName);

    ncwriteatt(outFile,'/','summary', ...
        'Derived NetCDF product preserving trajectory time, latitude, and longitude, and adding ERA5 air temperature, SM-LG snow depth, FDD draft, and thermal-resistance draft.');

    ncwriteatt(outFile,'/','trajectory_direction', ...
        'Row 1 is the trajectory arrival point. Increasing row index follows the back trajectory backward in time.');

    ncwriteatt(outFile,'/','note', ...
        'Original trajectory NetCDF files were not modified.');

    ncwriteatt(outFile,'/','created_by', ...
        'export_backtrajectories_with_forcing_and_draft.m');

    ncwriteatt(outFile,'/','creation_date', ...
        char(datetime('now','Format','yyyy-MM-dd HH:mm:ss')));

end

function write_2d_var(outFile,varName,data,longName,units,comment)

    [nStep,nTraj] = size(data);

    nccreate(outFile,varName, ...
        'Dimensions',{'time_step',nStep,'trajectory',nTraj}, ...
        'Datatype','double', ...
        'FillValue',NaN, ...
        'DeflateLevel',4);

    ncwrite(outFile,varName,data);

    ncwriteatt(outFile,varName,'long_name',longName);
    ncwriteatt(outFile,varName,'units',units);
    ncwriteatt(outFile,varName,'comment',comment);

end

function write_1d_var(outFile,varName,data,longName,units,comment)

    data = data(:);
    nTraj = length(data);

    nccreate(outFile,varName, ...
        'Dimensions',{'trajectory',nTraj}, ...
        'Datatype','double', ...
        'FillValue',NaN, ...
        'DeflateLevel',4);

    ncwrite(outFile,varName,data);

    ncwriteatt(outFile,varName,'long_name',longName);
    ncwriteatt(outFile,varName,'units',units);
    ncwriteatt(outFile,varName,'comment',comment);

end

function check_same_size(A,B,nameA,nameB)

    if ~isequal(size(A),size(B))
        error('Size mismatch: %s is %s, but %s is %s.', ...
            nameA, mat2str(size(A)), nameB, mat2str(size(B)));
    end

end